# Generated by Django 5.0 on 2024-01-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_customuser_is_active_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('posted_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
